### ISSUE TITLE
文件路径错误

### ISSUE THREAD

**Issue by BSSNBSSN** [HBUTHUANGPX/Hbut_LC_sentry#1]
`Hbut_LC_sentry/RMUS_map_ws/src/rmus_map_2/launch/`中两个launch文件`gazebo.launch`与`display.launch`存在路径错误
```
$(find rmus_map_2)/urdf/rmus_map_2.urdf
```
应为
```
$(find rmus_map_2)/urdf/RMUS_map_2.urdf
```

**Comment by HBUTHUANGPX** [comment]
我已将RMUS_map_2.urdf更名为rmus_map_2.urdf
